name: Formatting/static analysis
on:
  pull_request:
  push:
    branches:
      - master
    paths:
      - pokerpy/**
      - tests/**
      - .github/workflows/static_analysis.yaml

jobs:
  analysis:
    name: Formatting and static analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Update pip
        run: python -m pip install --upgrade pip
      - name: Black check
        run: |
          pip install black
          black --check --target-version=py37 .
