name: Test suite
on:
  pull_request:
  push:
    branches:
      - master
    paths:
      - pokerpy/**
      - tests/**
      - .github/workflows/test.yaml

jobs:
  Pytest:
    name: Pytest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Update pip
        run: python -m pip install --upgrade pip
      - name: Pytest
        run: |
          pip install pytest
          pytest .
